import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#3f63d8',
    primaryColorHover: '#5376e4',
    primaryColorPressed: '#3151bd',
    primaryColorSuppl: '#3f63d8',
    infoColor: '#3f63d8',
    infoColorHover: '#5376e4',
    infoColorPressed: '#3151bd',
    infoColorSuppl: '#3f63d8',
    successColor: '#229b6b',
    successColorHover: '#32ad7c',
    successColorPressed: '#198057',
    successColorSuppl: '#229b6b',
    textColorBase: '#172033',
    textColor1: '#172033',
    textColor2: '#4b5565',
    textColor3: '#7d8798',
    placeholderColor: '#a1a9b7',
    dividerColor: '#edf0f5',
    borderColor: '#e2e7ef',
    bodyColor: '#f4f6fa',
    cardColor: '#ffffff',
    tableHeaderColor: '#f7f9fc',
    hoverColor: '#f3f6ff',
    tableColorHover: '#f4f7ff',
    borderRadius: '10px',
    borderRadiusSmall: '8px',
    boxShadow1: '0 8px 24px rgba(15, 23, 42, 0.05)',
    boxShadow2: '0 14px 36px rgba(15, 23, 42, 0.08)',
  },
  Card: {
    borderRadius: '14px',
    borderColor: '#e7ebf2',
    paddingMedium: '20px 22px',
    titleTextColor: '#172033',
    titleFontWeight: '600',
    boxShadow: '0 8px 24px rgba(15, 23, 42, 0.05)',
  },
  Button: {
    borderRadiusMedium: '9px',
    borderRadiusSmall: '8px',
    fontWeight: '500',
  },
  Input: {
    borderRadius: '9px',
  },
  Select: {
    peers: {
      InternalSelection: {
        borderRadius: '9px',
      },
    },
  },
  DataTable: {
    borderRadius: '10px',
    borderColor: '#edf0f5',
    thColor: '#f7f9fc',
    thColorHover: '#f3f6fb',
    thTextColor: '#3d4758',
    thFontWeight: '600',
    tdColorHover: '#f4f7ff',
  },
  Menu: {
    borderRadius: '10px',
    itemColorHover: '#f4f6fb',
    itemColorActive: '#edf2ff',
    itemColorActiveHover: '#e7edff',
    itemColorActiveCollapsed: '#edf2ff',
    itemTextColorActive: '#3658c7',
    itemTextColorActiveHover: '#3151bd',
    itemTextColorChildActive: '#3658c7',
    itemTextColorChildActiveHover: '#3151bd',
    arrowColorActive: '#3658c7',
    arrowColorChildActive: '#3658c7',
  },
  Layout: {
    color: '#f4f6fa',
    siderColor: '#ffffff',
    headerColor: '#ffffff',
  },
}
